apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
      {{- if .Values.network.name }}
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      hostname: example.com
      {{- end }}
