apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pyomo.name" . }}
    helm.sh/chart: {{ include "pyomo.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pyomo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pyomo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
        env:
          - name: NAME
            value: {{ .Values.nameOverride }}
